config/routes.rb
require 'api_constraints'
Task::Application.routes.draw do
   #devise_for :users

  #resources :users    
    devise_for :users, :controllers => { :registrations => "user/registrations",:sessions => "user/sessions" }
    
    # resources :users
    # root "users#home"
    devise_scope :user do
      authenticated :user do
        root 'user/sessions#destroy', as: :authenticated_root
      end

      unauthenticated do
        root 'devise/sessions#new', as: :unauthenticated_root
      end
    end

  scope 'admin' do
    resources :users 
  end

   


  

   #Redirects us to homepage

namespace :api , defaults: {format: 'json'} do
     # scope module: :v1, constraints: ApiConstraints.new(version: 1) do
    namespace :v1 do
       get "admin" => "users#admin"
       post "admin" => "users#admin"
       get "custshow" => "users#cust_index"
       #post "/custshow" => "users#cust_index"
       
       
    end
    
  end
       get "users/:id" => "users#show", as: :show_user
       get "users/:id/delete" => "users#destroy"
       get "home" => "users#home"
       get "other" => "users#other" 
       get "admin" => "users#admin"
       get "custshow" => "users#cust_index"
       get "customer" => "users#cust"
       post "cust" => "users#cust_create" 
       
       get "custshow/:id/delete" => "users#cust_destroy"
       get "custshow/:id/edit" => "users#cust_edit" ,as: :edit_customer
       patch "customer" => "users#cust_update"
       get "users/:id/block" => "users#block" 
       get "custshow/:id/appointment" => "users#appointment"

       get "prescription" => "users#pricri",as: :prescription
       post "prescri" => "users#pricription"

       get "prescriptionlist" => "users#prescri_list"

       get "prescrishow/:id/edit" => "users#prescri_edit" ,as: :edit_prescription
       patch "prescription" => "users#prescri_update"

       get "image" => "users#show_image"
       post "appointment_date" => "users#appointment_date"

       get "change_pwd/:id/edit" => "users#edit_user" ,as: :edit_password
       patch "change" => "users#update_user"

       post "send_appointment" => "users#send_appointment", as: :send_appointment

       get "change_image/:id/edit" => "users#edit_image" ,as: :edit_image
       patch "alterimage" => "users#update_image"
       get "cust_image/:id/delete" => "users#custimage_destroy"

  # Redirects us to admin page

   # Redirects us to other than admin page

  
 
  # get "users/detail" => "users#detail"


 # get "users/show/:d" => "user#show"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  has_many :customers
  validates :firstname, presence: true
  validates_presence_of :username


     mount_uploader :avatar, AvatarUploader
    attr_accessor :login


   def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  else
    if conditions[:username].nil?
      where(conditions).first
    else
      where(username: conditions[:username]).first
    end
  end
 end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      respond_to :json
      
      def admin
        respond_with User.all 
      end

     def cust_index
        respond_with Customer.all
     end

     # def home
     # end

    end
  end
end

app/controllers/api/v2/users_controller.rb
module Api
  module V2
    class UsersController < ApplicationController
      respond_to :json
      
      def admin
        respond_with User.all 
      end

      def cust_index
        respond_with Customer.all
     end
     # def home
     # end

    end
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
 class User::RegistrationsController < Devise::RegistrationsController
# # before_filter :configure_sign_up_params, only: [:create]
# # before_filter :configure_account_update_params, only: [:update]

#   # GET /resource/sign_up
#   # def new
#   #   super
#   # end

#   # POST /resource
#   # def create
#   #   super
#   # end

#   # GET /resource/edit
#   # def edit
#   #   super
#   # end

#   # PUT /resource
#   # def update
#   #   super
#   # end

#   # DELETE /resource
#   # def destroy
#   #   super
#   # end

#   # GET /resource/cancel
#   # Forces the session data which is usually expired after sign
#   # in to be expired now. This is useful if the user wants to
#   # cancel oauth signing in/up in the middle of the process,
#   # removing all OAuth session data.
#   # def cancel
#   #   super
#   # end

#   # protected

#   # You can put the params you want to permit in the empty array.
#   # def configure_sign_up_params
#   #   devise_parameter_sanitizer.for(:sign_up) << :attribute
#   # end

#   # You can put the params you want to permit in the empty array.
#   # def configure_account_update_params
#   #   devise_parameter_sanitizer.for(:account_update) << :attribute
#   # end

#   # The path used after sign up.
#   # def after_sign_up_path_for(resource)
#   #   super(resource)
#   # end

#   # The path used after sign up for inactive accounts.
#   # def after_inactive_sign_up_path_for(resource)
#   #   super(resource)
#   # end
#      protected
#   def after_update_path_for(resource)
#     if @user = current_user.admin?
#       '/admin'
#     else
#        '/other'      
#     end
# end
 end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end


 def create
   if params[:device].present?
     #build_resource
    resource = User.find_for_database_authentication(:login=>params[:username])
    
    # return invalid_login_attempt unless resource
    if resource.nil?
      render :status => 401, :json => "Invalid User name"  
    else
      if resource.valid_password?(params[:password])
        sign_in("user", resource)
        render :status => 200, :json => "success  "
        return
      else 
        render :status => 401, :json => "Invalid password"
      end
    end
    else
      super
   end
end


  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def invalid_login_attempt
    warden.custom_failure!
    render :json=> {:success=>false, :message=>"Error with your login or password"}, :status=>401
  end

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_appointment_date.html.erb
<center><h1>Appointment</h1></center>
  <%= form_tag url_for(:controller => 'users', :action => 'send_appointment'), :method => 'post' do |f| %>  
   
    <p class="ex1"> 
       Appointment Date :
      <%= select_datetime(updappointment = Time.current, options = {order: [:day, :month, :year]}, html_options = {})  %>
      <%= hidden_field_tag :cust_id,params[:data1]%>
    </p>

 <%= submit_tag "Submit",:class => "btn btn-info" %> 
       
<%end%>

app/views/users/_customer_attachment_fields.html.erb
</script>
<style>
p.ex1 {
    padding: 0.3cm 2cm;
}
</style>
<p class="ex1">
	<%= f.file_field :avatar %>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remove" %>
    <%#= link_to_remove_fields "remove", f %>
    <%#= f.link_to_remove "remove" %>
</p>
	

app/views/users/cust_edit.html.erb
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/base/jquery-ui.css" %>
<script type="text/javascript" src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript">
    jQuery(function($){
       $("#customer_dob").datepicker({changeMonth: true,
      changeYear: true,
      selectOtherMonths: true,
      dateFormat: "mm/dd/yy" ,
      yearRange: "1900:2050",
       maxDate: '+0d',
    onSelect: function (date) {
      var dob = new Date(date);
      var today = new Date();
      var age = today.getFullYear()-dob.getFullYear() ;
      var a = age;
      document.getElementById("customer_age").value = a;
    }
        });
</script>
<html>
<head>
  <style>
    p.ex1 {
        padding: 0.3cm 2cm;
      }
  </style>
</head>

<div id="content" class="col-lg-10 col-sm-10">
  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a>
      </li>
      <li>  
        <a href="#">Tables</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">

<body style="background:none;">
<center><h1> Edit Form </h1></center>
<%= form_for @user1 do |f| %>
 
   <% if @user1.errors.any? %>  
        <div class="error_messages">  
          <h2><%= pluralize(@user1.errors.count, "error") %> prohibited this user from being saved:</h2>  
          <ul>  
              <% @user1.errors.full_messages.each do |msg| %>  
                <li><%= msg %></li>  
              <% end %>  
          </ul>  
        </div>  
  <% end %>  
 
    <% if current_user.role == "doctor"%>
       <%= f.hidden_field :id, :value => @user1.id%>
       <%= f.hidden_field :doc_id, :value => current_user.id  %>
       <%= f.hidden_field :user_id, :value => current_user.user_id  %>
    <%elsif current_user.role == "reception"%>
       <%= f.hidden_field :id, :value => @user1.id%>
       <%= f.hidden_field :reception_id, :value => current_user.id  %>
       <%= f.hidden_field :user_id, :value => current_user.user_id  %>
    <%else current_user.role == "admin"%>
        <%= f.hidden_field :id, :value => @user1.id%>
        <%= f.hidden_field :user_id, :value => current_user.id  %>
    <%end%>

    <p class="ex1">
      <%= f.label "Full Name" %><br />
      <%= f.text_field :name, autofocus: true,:required => true,:style => "border: 1px black solid; color: black;"%>
    </p>
      
    <p class="ex1">
      <%= f.label "Date Of Birth" %><br />
      <%= f.text_field :dob, :class => 'text_field' , :autocomplete=>"off",:readonly => true,:style => "border: 1px black solid; color: black;"  %>
    </p>

    <p class="ex1">
      <%= f.label "Age" %><br />
      <%= f.text_field :age, :class => 'text_field' , :required => "true",:style => "border: 1px black solid; color: black;" %>
    </p>
      
    
     <!--  <p class="ex1">
      <%#= f.file_field :avatar %>  
    </p>  -->
     <%#= f.fields_for :customer_attachments do |builder| %>
        <%#= render "customer_attachment_fields", :f  => builder %>
    <%#end %>
    <!-- <p class="ex1"><%#= link_to_add_fields "Add Attachment", f, :customer_attachments %></p> -->

    <%if current_user.role == "reception" || current_user.role == "admin"%>
      <p class="ex1">
        <%= f.label "Doctor"%><br />
        <%= f.collection_select :doc_id, @user,:id, :firstname ,:prompt =>"Please Select Doctor"%>
      </p> 
    <%end%>
    <p class="ex1">
      <%= f.submit "Update",:class => "btn btn-info" %>
      <%if current_user.role == "super_admin" || current_user.role == "admin" %>
         <%= link_to "Cancel", admin_path,:class => "btn btn-info" %>
      <%else%>
         <%= link_to "Cancel", custshow_path,:class => "btn btn-info" %>
      <%end%>
    </p>
   <% end %>
</body>


</div>
      </div>
    </div>
  </div> 
</div>

app/views/users/cust_index.html.erb
 <%= javascript_include_tag "facebox.js" %>
 <%= stylesheet_link_tag "facebox.css" %>
<script>   
    function myFunction(a) {
    	  var id = a; 
          $.ajax({
          type: "POST",
          data: {data1 : id},
          url: "<%= appointment_date_path %>",
          });
    };
</script>
<div id="content" class="col-lg-10 col-sm-10">
	<div>
		<ul class="breadcrumb">
			<li>
				<a href="#">Home</a>
			</li>
			<li>	
				<a href="#">Tables</a>
			</li>
		</ul>
	</div>

	<div class="row">
		<div class="box col-md-12">
			<div class="box-inner">
				<div class="box-header well" data-original-title="">
					<h2><i class="glyphicon glyphicon-user"></i> Datatable</h2>
				</div>

				<%if current_user.role == "admin" || current_user.role =="super_admin"%>
				<div class="box-content">
					<div class="alert alert-info"> 
						<a class="btn btn-info" href="/admin/users/new">Add New User</a>
						<a class="btn btn-info" href="/customer" data-no-turbolink="true">Add New Customer</a>
						<a class="btn btn-info" href="/custshow">Show Customer</a>
					</div>
					<%else%>

                      <div class="box-content">
					  <div class="alert alert-info">
					  <a class="btn btn-info" href="/customer" data-no-turbolink="true">Add New Customer</a>
					 <a class="btn btn-info" href="/custshow">Show Customer</a>
					</div> 
					<%end%>

					<div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
							<thead>
							<tr>
								<th>Index No.</th>
								<th>Full Name</th>
								<th>Age</th>
								<th>Image</th>
								<th>Register Date</th>
								<th>Appoinment Date</th>
								<th>Action</th>
							</tr>
							</thead>
							<body style="background:none;">
								<% @user1.each_with_index do |f,index| %>
									<tr>
										<% index += 1%>
										<td><%= index %></td>
										<td class="center"><%= f.name %></td>
										<td class="center"><%= f.age %></td>
										<%if f.avatar == nil %>
											<%if f.customer_attachments == []%>
											    <td><%= %></td>
	                                        <%else%>
	                                              <td class="center"><% f.customer_attachments.each_with_index do |p,i| %>
		                                               <%i+=1%>
		                                               <%= i%>.=>
											           <%=(link_to p.avatar_url,image_path(:id => f.id,:avatar => p.id),target: "_blank")%> 
											                <br />
											           <%end%>
											       </td>
											<%end%>
                                        <%else%>
                                            <td><%= %></td>
										<%end%>
										
									    <td class="center"><%= f.created_at.to_date %></td>
									    <td class="center"><%= f.updappointment%></td>
										<td class="center">
											<a class="btn btn-info" href="/custshow/<%= f.id %>/edit"><i class="glyphicon glyphicon-edit icon-white"></i>
										     Edit</a>
											<a class="btn btn-danger" href="/custshow/<%= f.id %>/delete" onclick="if(confirm('Are you sure you want to delete this Data?'))  return true;  else  return false;" class="button negative"><i class="glyphicon glyphicon-trash icon-white"></i>Delete</a>

											<%= link_to  "javascript:void(0);",:onclick=>"myFunction(#{f.id})", :class=>"btn btn-info"  do %>
											     <i class="glyphicon glyphicon-edit icon-white"></i>Appoinment
											<%end%>

											<% if current_user.role == "doctor"%>
	                                            <%= link_to prescriptionlist_path(:customer => f.id), :class=>"btn btn-danger" do%>
	                                            <i class="glyphicon glyphicon-trash icon-white"></i>Show Prescription
	                                            <%end%>
                                            <%end%>
										</td>
									</tr>
								<%end%>
							</body>
						</table>
						  <%if current_user.role == "super_admin" || current_user.role == "admin" %>
					         <%= link_to "Cancel", admin_path,:class => "btn btn-info" %>
					      <%else%>
					         <%= link_to "Cancel", custshow_path,:class => "btn btn-info" %>
					      <%end%>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

app/views/users/edit.html.erb
<html>

  <style>
    p.ex1 {
        padding: 0.3cm 2cm;
      }
  </style>


<div id="content" class="col-lg-10 col-sm-10">
  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a>
      </li>
      <li>  
        <a href="#">Tables</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">

<body style="background:none;">
<center><h1> Edit Form </h1></center>
<%= form_for @user do |f| %>
 <% if @user.errors.any? %>  
  <div class="error_messages">  
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>  
    <ul>  
    <% @user.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
  <% end %>  

 <% if current_user.role == "admin"%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
 <%end%>

 <p class="ex1">
    <%= f.label "Full Name" %><br />
    <%= f.text_field :firstname, autofocus: true,:style => "border: 1px black solid; color: black;"%>
 </p>
  
  <p class="ex1">
    <%= f.label "User Name" %><br />
    <%= f.text_field :username,:style => "border: 1px black solid; color: black;" %>
  </p>
    
  <p class="ex1">
    <%= f.label "Email Id" %><br />
    <%= f.email_field :email,:style => "border: 1px black solid; color: black; padding:0.7em 2em 0.7em 1.7em;" %>
  </p>

  <p class="ex1">
    <%= f.label "Password" %><br />
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password,autocomplete: "off",:style => "border: 1px black solid; color: black;" %>
  </p>

  <p class="ex1">
    <%= f.label "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation,autocomplete: "off",:style => "border: 1px black solid; color: black;" %>
  </p>
  <p class="ex1">
    <%= f.label "Roles" %><br />
           <% if current_user.role == "super_admin"%>
            <%= f.radio_button :role, 'admin' %> 
            <%= f.label :role, 'Admin', :value => 'admin' %>
           <%end%>
      <%= f.radio_button :role, 'doctor' %> 
      <%= f.label :role, 'Doctor', :value => 'doctor' %>
      <%= f.radio_button :role, 'reception' %> 
      <%= f.label :role, 'Reception', :value => 'reception' %>
  </p>

  <p class="ex1">
      <%= f.collection_select :speciality_id, @specility, :id, :speciality_name,:prompt =>"Please Select Specilization for Doctor Only"  %>
  </p>
  
  <p class="ex1">
    <%= f.submit "Update",:class => "btn btn-info" %> 
    <%= link_to "Cancel", admin_path,:class => "btn btn-info" %>
  </p>
<% end %>
</body>
</div>
      </div>
    </div>
  </div> 
</div>

app/views/users/edit_image.html.erb
<html>
  <style>
    p.ex1 {
        padding: 0.3cm 2cm;
      }
  </style>


<div id="content" class="col-lg-10 col-sm-10">
  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a>
      </li>
      <li>  
        <a href="#">Tables</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">

<body style="background:none;">
<center><h1> Edit Image </h1></center>
<%= form_for @image ,:url => url_for(:controller => 'users', :action => 'update_image') do |f| %>
   
 
     <p class="ex1">
          <%= f.file_field :avatar %>  
      </p> 
     <%= f.hidden_field :id, :value => @image.id%>
    <p class="ex1">
      <%= f.submit "Update",:class => "btn btn-info" %>
      <%if current_user.role == "super_admin" || current_user.role == "admin" %>
         <%= link_to "Cancel", admin_path,:class => "btn btn-info" %>
      <%else%>
         <%= link_to "Cancel", custshow_path,:class => "btn btn-info" %>
      <%end%>
    </p>
   <% end %>
</body>


</div>
      </div>
    </div>
  </div> 
</div>

app/views/users/new.html.erb
<html>

  <style>
    p.ex1 {
        padding: 0.3cm 2cm;
      }
  </style>


<div id="content" class="col-lg-10 col-sm-10">
  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a>
      </li>
      <li>  
        <a href="#">Tables</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">

<body style="background:none;">
<center><h1>New user</h1></center>
  <%= form_for(@user) do |f| %>
   
     <% if @user.errors.any? %>  
        <div class="error_messages">  
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>  
          <ul>  
            <% @user.errors.full_messages.each do |msg| %>  
            <li><%= msg %></li>  
            <% end %>  
          </ul>  
        </div>  
    <% end %> 

  <% if current_user.role == "admin"%>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <%end%>

    <p class="ex1">
      <%= f.label "Full Name" %><br />
      <%= f.text_field :firstname, autofocus: true,:required => true,:style => "border: 1px black solid; color: black;" %>
    </p>
  
    <p class="ex1">
      <%= f.label "User Name" %><br />
      <%= f.text_field :username,:required => true,:style => "border: 1px black solid; color: black;" %>
    </p>

    <p class="ex1">
      <%= f.label "Email Id" %><br />
      <%= f.email_field :email,:required => true,:style => "border: 1px black solid; color: black; padding:0.7em 2em 0.3em 1.7em;" %>
    </p>

    <p class="ex1">
      <%= f.label "Password" %>
      <% if @validatable %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off",:required => true,:style => "border: 1px black solid" %>
    </p>

    <p class="ex1">
      <%= f.label "Password Confirmation" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off",:required => true,:style => "border: 1px black solid" %>
    </p>

  <!-- <div> -->
    <p class="ex1">
        <%= f.label "Roles" %><br />
           <% if current_user.role == "super_admin"%>
            <%= f.radio_button :role, 'admin' %> 
            <%= f.label :role, 'Admin', :value => 'admin' %>
           <%end%>
        <%= f.radio_button :role, 'doctor' %> 
        <%= f.label :role, 'Doctor', :value => 'doctor' %>
        <%= f.radio_button :role, 'reception' %> 
        <%= f.label :role, 'Reception', :value => 'reception' %>
    </p>
    <p class="ex1">
      <%= f.collection_select :speciality_id, @specility, :id, :speciality_name,:prompt =>"Please Select Specilization for Doctor Only"%>
    </p>
    <p class="ex1">
      <%= f.submit "Create",:class => "btn btn-info" %> 
      <%= link_to "Cancel", admin_path,:class => "btn btn-info" %>
    </p>
  <% end %>
</body>

</div>
      </div>
    </div>
  </div> 
</div>

app/views/users/prescri_list.html.erb
<div id="content" class="col-lg-10 col-sm-10">
  <div>
    <ul class="breadcrumb">
      <li>
        <a href="#">Home</a>
      </li>
      <li>  
        <a href="#">Tables</a>
      </li>
    </ul>
  </div>

  <div class="row">
    <div class="box col-md-12">
      <div class="box-inner">

<%if @user_doctor == []%>
 <center><h2><%= flash[:notice] = "There is Not Giving Any Prescription Yet by Doctor."%></h2></br>
    <%= link_to "Back", custshow_path,:class => "btn btn-info" %>
    <%= link_to"Prescription", prescription_path(:customer => params[:customer]), :class=>"btn btn-info"%>
 </center>

<%else%>

   
<style>
p.ex1 {
    padding: 0.3cm 4.3cm;
}
</style>

   <center><h3>Prescription Page</h3></center>
    <article>
      <header>
      	<% @user_doctor.each_with_index do |f,index|%>
      	  <h2><p class="ex1">Description :</p></h2>
          <h3><p class="ex1"><%= f.description %></p></h3>
          </header>     
      	  <% index += 1%>
          <h3><p class="ex1"><%= index %>. Prescription Date</p></h3>
          <h4><p class="ex1"><%= f.date_current %></p></h4>
          <h3><p class="ex1">Prescription</p></h3>
          <h4><p class="ex1"><%= f.precription %></p></h4>
      	<%end%>
	</article>
	<p class="ex1">
		<%= link_to "Back", custshow_path,:class => "btn btn-info" %>
    <%= link_to"Prescription", prescription_path(:customer => params[:customer]), :class=>"btn btn-info" %>
  </p>                                            
  <%end%>
	</div>
   </div>
  </div>
 </div> 
</div>

app/views/users/show.html.erb
  
<style>
p.ex1 {
    padding: 0.3cm 5.5cm;
}
</style>

   <center><h3>Details Page</h3></center>
    <article>
      <header>
        <h1><%= @user.email %></h1>
      </header>
  <h3>Full Name</h3>
  <p>
    <%= @user.firstname %>
  </p>
  
  <h3>User Name</h3>
  <p>
    <%= @user.username %>
  </p>
 
  <h3>Email</h3>
  <p>
    <%= @user.email %>
  </p>
  <h3>Role</h3>
  <p>
    <%= @user.role %>
  </p>
</article>
<p class="ex1">
<%= link_to "Back", other_path,:class => "btn btn-info" %></p>